/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Abono;
import ar.com.ventas.entities.Direccion;
import ar.com.ventas.entities.RenglonAbono;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.AbonoService;
import ar.com.ventas.services.RenglonAbonoService;
import ar.com.ventas.utils.UtilFrame;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class AbmAbonoFrame extends javax.swing.JFrame {

    private List<Abono> abonos = null;
    private DecimalFormat df = new DecimalFormat("#0.00");

    /**
     * Creates new form AbmAbonoFrame
     */
    public AbmAbonoFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        nuevoBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAbonos = new javax.swing.JTable();
        eliminarBtn = new javax.swing.JButton();
        eliminadosBtn = new javax.swing.JButton();
        habilitarBtn = new javax.swing.JButton();
        bloquearBtn = new javax.swing.JButton();
        modificarImportesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ABM ABONOS");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        nuevoBtn.setText("Nuevo");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        tablaAbonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Rubro", "CLIENTE", "IMPORTE", "PERIODO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAbonos);

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        eliminadosBtn.setText("Eliminados");

        habilitarBtn.setText("Habilitar Período");
        habilitarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarBtnActionPerformed(evt);
            }
        });

        bloquearBtn.setText("Bloquear Período");
        bloquearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquearBtnActionPerformed(evt);
            }
        });

        modificarImportesBtn.setText("Modificar Importes X Rubro");
        modificarImportesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarImportesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(modificarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(eliminadosBtn)
                        .addGap(18, 18, 18)
                        .addComponent(habilitarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(bloquearBtn)
                        .addGap(18, 18, 18)
                        .addComponent(modificarImportesBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoBtn)
                    .addComponent(modificarBtn)
                    .addComponent(volverBtn)
                    .addComponent(eliminarBtn)
                    .addComponent(eliminadosBtn)
                    .addComponent(habilitarBtn)
                    .addComponent(bloquearBtn)
                    .addComponent(modificarImportesBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        nuevo();
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        modificar();
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void habilitarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarBtnActionPerformed
        habilitar();
    }//GEN-LAST:event_habilitarBtnActionPerformed

    private void bloquearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquearBtnActionPerformed
        bloquear();
    }//GEN-LAST:event_bloquearBtnActionPerformed

    private void modificarImportesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarImportesBtnActionPerformed
        modificarImportes();
    }//GEN-LAST:event_modificarImportesBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        int row = tablaAbonos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNO PARA ELIMINAR");
            return;
        }
        eliminar(row);
    }//GEN-LAST:event_eliminarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbmAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbmAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbmAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbmAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbmAbonoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloquearBtn;
    private javax.swing.JButton eliminadosBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton habilitarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JButton modificarImportesBtn;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JTable tablaAbonos;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void llenarTabla() {
        DefaultTableModel tbl = (DefaultTableModel) tablaAbonos.getModel();
        abonos = null;
        try {
            abonos = new AbonoService().getAllAbonosActivosOrdenado();
        } catch (Exception ex) {
            Logger.getLogger(AbmAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (abonos != null && !abonos.isEmpty()) {
            UtilFrame.limpiarTabla(tablaAbonos);
            for (Abono ab : abonos) {
                Object ob[] = new Object[5];
                ob[0] = ab.getCodigo();
                Direccion dm = ab.getCliente().getDireccion();
                ob[1] = ab.getRubro().getDetalle();
                ob[2] = dm.getCalle() + " " + dm.getNumero();
                ob[3] = df.format(ab.getImporte());
                if (ab.getGenerado() != null) {
                    if (ab.getGenerado()) {
                        ob[4] = "GENERADO";
                    } else {
                        ob[4] = "habilitado";
                    }
                } else {
                    ob[4] = "GENERADO";
                }
                tbl.addRow(ob);
            }
            tablaAbonos.setModel(tbl);
        }
    }

    private void nuevo() {
        NuevoAbonoFrame naf = new NuevoAbonoFrame();
        naf.setVisible(true);
        this.dispose();
    }

    private void modificar() {
        int row = tablaAbonos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN ABONO PARA MODIFICAR");
            return;
        }
        Abono a = abonos.get(row);
        ModificarAbonoFrame maf = new ModificarAbonoFrame(a);
        maf.setVisible(true);
        this.dispose();
    }

    private void habilitar() {
        int row = tablaAbonos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "SELECCIONE CUAL QUIERE HABILITAR");
            return;
        }
        Abono ab = abonos.get(row);
        ab.setGenerado(false);
        try {
            new AbonoService().updateAbono(ab);
        } catch (Exception ex) {
            Logger.getLogger(AbmAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        llenarTabla();
    }

    private void bloquear() {
        int row = tablaAbonos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "SELECCIONE CUAL QUIERE BLOQUEAR");
            return;
        }
        Abono ab = abonos.get(row);
        ab.setGenerado(true);
        try {
            new AbonoService().updateAbono(ab);
        } catch (Exception ex) {
            Logger.getLogger(AbmAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        llenarTabla();
    }

    private void modificarImportes() {
        CambiarImportesPorRubroFrame ciprf = new CambiarImportesPorRubroFrame();
        ciprf.setVisible(true);
        this.dispose();
    }

    private void eliminar(int row) {
        Abono ab = abonos.get(row);
        List<RenglonAbono> renglones;
        try {
            renglones = new RenglonAbonoService().getRenglonAbonosByAbono(ab);
        } catch (Exception ex) {
            Logger.getLogger(AbmAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        int a = JOptionPane.showConfirmDialog(this, "CONFIRME ELIMINAR ABONO",
                 "Atención", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                new AbonoService().deleteAbonoCompleto(ab, renglones);
            } catch (Exception ex) {
                Logger.getLogger(AbmAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
