/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Cliente;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.ClienteService;
import ar.com.ventas.utils.UtilFrame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class ClientesEliminadosFrame extends javax.swing.JFrame {

    private List<Cliente> clientes = null;

    /**
     * Creates new form AbmClienteFrame
     */
    public ClientesEliminadosFrame() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        activarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CLIENTES ELIMINADOS");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "R.S.", "Dirección", "CUI", "Mau", "Período Hab."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaClientes);
        if (tablaClientes.getColumnModel().getColumnCount() > 0) {
            tablaClientes.getColumnModel().getColumn(0).setPreferredWidth(30);
            tablaClientes.getColumnModel().getColumn(1).setPreferredWidth(160);
            tablaClientes.getColumnModel().getColumn(3).setPreferredWidth(80);
            tablaClientes.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        activarBtn.setText("Activar");
        activarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(activarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void activarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarBtnActionPerformed
        int row = tablaClientes.getSelectedRow();
        if(row < 0){
            return;
        }
        Cliente c = clientes.get(row);
        activar(c);
    }//GEN-LAST:event_activarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesEliminadosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        AbmClienteFrame mf = new AbmClienteFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void llenarTabla() {
        UtilFrame.limpiarTabla(tablaClientes);
        clientes = null;
        try {
            clientes = new ClienteService().getAllClientesInactivos();
        } catch (Exception ex) {
            Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (clientes != null && !clientes.isEmpty()) {
            DefaultTableModel tbl = (DefaultTableModel) tablaClientes.getModel();
            for (Cliente cli : clientes) {
                Object ob[] = new Object[6];
                ob[0] = cli.getCodigo();
                ob[1] = cli.getRazonSocial();
                ob[2] = cli.getDireccion().getCalle() + " " + cli.getDireccion().getNumero();
                ob[3] = cli.getCuit();
                ob[4] = cli.getCodigoMauro();
//                if (cli.getGenerado()) {
//                    ob[5] = "Generado";
//                } else {
//                    ob[5] = "Habilitado";
//                }
                tbl.addRow(ob);
            }
            tablaClientes.setModel(tbl);
        }
    }

    private void nuevo() {
        NuevoClienteFrame ncf = new NuevoClienteFrame();
        ncf.setVisible(true);
        this.dispose();
    }

    private void modificar() {
        int row = tablaClientes.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecciones un cliente");
            return;
        }
        ModificarClienteFrame mcf = new ModificarClienteFrame(clientes.get(row));
        mcf.setVisible(true);
        this.dispose();
    }

//    private void habilitarPeriodo() {
//        int row = tablaClientes.getSelectedRow();
//        if (row < 0) {
//            JOptionPane.showMessageDialog(this, "Seleccione 1 Cliente");
//            return;
//        }
//        int a = JOptionPane.showConfirmDialog(this, "Confirme Habilitar Período", "Atención", JOptionPane.YES_NO_OPTION);
//        if (a == 0) {
//            Cliente c = clientes.get(row);
//            c.setGenerado(false);
//            try {
//                new ClienteService().updateCliente(c);
//            } catch (Exception ex) {
//                Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            llenarTabla();
//        }
//    }

//    private void bloquear() {
//        int row = tablaClientes.getSelectedRow();
//        if (row < 0) {
//            JOptionPane.showMessageDialog(this, "Seleccione 1 Cliente");
//            return;
//        }
//        int a = JOptionPane.showConfirmDialog(this, "Confirme Habilitar Período", "Atención", JOptionPane.YES_NO_OPTION);
//        if (a == 0) {
//            Cliente c = clientes.get(row);
//            c.setGenerado(true);
//            try {
//                new ClienteService().updateCliente(c);
//            } catch (Exception ex) {
//                Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            llenarTabla();
//        }
//    }

    private void asignarTitular() {
        int row = tablaClientes.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN CLIENTE");
            return;
        }
        Cliente cl = clientes.get(row -1);
        AsignarTitularAlClienteFrame atacf = new AsignarTitularAlClienteFrame(cl);
        atacf.setVisible(true);
        this.dispose();
    }

    private void activar(Cliente c) {
        c.setActivo(true);
        try {
            new ClienteService().updateCliente(c);
        } catch (Exception ex) {
            Logger.getLogger(ClientesEliminadosFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
