/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Abono;
import ar.com.ventas.entities.Cliente;
import ar.com.ventas.entities.Configuracion;
import ar.com.ventas.entities.Factura;
import ar.com.ventas.entities.RenglonAbono;
import ar.com.ventas.entities.RenglonRubro;
import ar.com.ventas.entities.RenglonFactura;
import ar.com.ventas.entities.Rubro;
import ar.com.ventas.entities.TicketTime;
import ar.com.ventas.entities.TitularCuit;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.AbonoService;
import ar.com.ventas.services.ClienteService;
import ar.com.ventas.services.ConfiguracionService;
import ar.com.ventas.services.FacturaService;
import ar.com.ventas.services.RenglonAbonoService;
import ar.com.ventas.services.RenglonFacturaService;
import ar.com.ventas.services.RubroService;
import ar.com.ventas.services.TicketTimeService;
import ar.com.ventas.services.TitularCuitService;
import ar.com.ventas.utils.UtilFactura;
import ar.com.ventas.utils.UtilFrame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.jacob.activeX.ActiveXComponent;
import com.jacob.com.Dispatch;
import com.jacob.com.LibraryLoader;
import com.jacob.com.Variant;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import static java.lang.Math.rint;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class GenerarAbonoFrame extends javax.swing.JFrame {

    private TicketTime tkt = null;
    private String token;
    private String sign;
    private String wsdl = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
    private String userdir = "c:/certiflou";
    private String excepcion = "";
    private ActiveXComponent wsaa;
    private List<Abono> abonos = null;
    private Integer hora = 0, minutos = 0, segundos = 0;
    private Date fecha;
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private String tipoComprob;
    private final DecimalFormat df = new DecimalFormat("#0.00");
    private String numeroFacturaPapel = "";
    private final String letraFacturaPapel = "L";
    private String sucursalFacturaPapel = "0";
    private String numCae = "";
    private String vencCae = "";
    private Integer comprobanteNumero = 0;
    private Integer tst = 1; // 1 es test
    private List<Rubro> rubros;

    /**
     * Creates new form AbonoFrame
     */
    public GenerarAbonoFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
        fechaTxt.setText(sdf.format(new Date()));
        calcularFechas();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        generarBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fecha1Txt = new javax.swing.JTextField();
        fecha2Txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboP = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fecha3Txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GENERAR ABONOS DE CLIENTES HABILITADOS");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("FECHA ABONOS:");

        fechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaTxt.setText("FECHA ABONO");

        generarBtn.setText("Generar");
        generarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("FECHA PERIODO DESDE:");

        jLabel3.setText("FECHA PERIODO HASTA:");

        fecha1Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha1Txt.setText("FECHA DDE");

        fecha2Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha2Txt.setText("FECHA HTA");

        jLabel4.setText("RUBRO:");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Producto/Servicio:");

        comboP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("FECHA VENCIMIENTO:");

        fecha3Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha3Txt.setText("FECHA VTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(250, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(comboP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(generarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volverBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(fecha1Txt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fecha2Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(fecha3Txt))))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fecha1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fecha2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fecha3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(generarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void generarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBtnActionPerformed
        int row = combo.getSelectedIndex();
        if (row > 0) {
            int rowP = comboP.getSelectedIndex();
            if (rowP > 0) {
                Rubro rubro = rubros.get(row - 1);
                generar(rubro);
            } else {
                JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR PRODUCTO/SERVICIO O AMBOS");
            }
        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN RUBRO");
        }

    }//GEN-LAST:event_generarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarAbonoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> comboP;
    private javax.swing.JTextField fecha1Txt;
    private javax.swing.JTextField fecha2Txt;
    private javax.swing.JTextField fecha3Txt;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton generarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void generar(Rubro rubro) {
        String fe;
        String fe1;
        String fe2;
        String fe3;
        Date da = new Date();
        Date da1 = new Date();
        Date da2 = new Date();
        Date da3 = new Date();
        int ps = comboP.getSelectedIndex();
        if(ps < 1){
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR PRODUCTO O SERVICIO");
            comboP.requestFocus();
            return;
        }
        if (!fechaTxt.getText().isEmpty()) {
            fe = fechaTxt.getText();
        } else {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA FECHA");
            fechaTxt.requestFocus();
            return;
        }
        if (!fecha1Txt.getText().isEmpty()) {
            fe1 = fecha1Txt.getText();
        } else {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA FECHA");
            fecha1Txt.requestFocus();
            return;
        }
        if (!fecha2Txt.getText().isEmpty()) {
            fe2 = fecha2Txt.getText();
        } else {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA FECHA");
            fecha2Txt.requestFocus();
            return;
        }
        if (!fecha3Txt.getText().isEmpty()) {
            fe3 = fecha3Txt.getText();
        } else {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA FECHA");
            fecha3Txt.requestFocus();
            return;
        }
        try {
            da = sdf.parse(fe);
            da1 = sdf.parse(fe1);
            da2 = sdf.parse(fe2);
            da3 = sdf.parse(fe3);
        } catch (ParseException ex) {
            Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        abonos = null;
        try {
            abonos = new AbonoService().getAbonosActivosByRubroAndClienteHabilitado(rubro); //AllClientesHabilitadosByRubro(rubro);
        } catch (Exception ex) {
            Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (abonos != null && !abonos.isEmpty()) {
            for (Abono ab : abonos) {
                Cliente cl = ab.getCliente();
                ab.setGenerado(true);
//                TitularCuit titu = null;
//                titu = new TitularCuitService().getAllTitularDeCuitActivos();
                List<RenglonAbono> ra = null;
//                cl.setGenerado(true);
                try {
                    ra = new RenglonAbonoService().getRenglonAbonosByAbono(ab);
                } catch (Exception ex) {
                    Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
//                System.out.println(cl.getDireccion().getCalle());
//                System.out.println(cl.getDireccion().getNumero());
//                System.out.println(ab.getRubro().getDetalle());
//                for (RenglonAbono ra1 : ra) {
//                    System.out.println(ra1.getOrden());
//                    System.out.println(ra1.getTexto());
//                }
//                System.out.println(ab.getImporte());
//                System.out.println("");
//                JOptionPane.showMessageDialog(this, "VER");
                String resultado = UtilFactura.saveFactura(cl, ab, ra, da, da1, da2, da3, ps);
                if (resultado.equals("N")) {
                    JOptionPane.showMessageDialog(this, "ERROR EN TRANSACCION");
                    return;
                }
            }
            volver();
        } else {
            JOptionPane.showMessageDialog(this, "VERIFIQUE NO HAY ABONOS PARA GENERAR");
        }
    }

//    private void generar() {
//        int numf = 0;
//        int suc = 6;
//        clientes = null;
//        try {
//            clientes = new ClienteService().getAllClientes();
//        } catch (Exception ex) {
//            Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        Long id = 1L;
//        Configuracion config = null;
//        try {
//            config = new ConfiguracionService().getConfiguracionById(id);
//        } catch (Exception ex) {
//            Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        numf += config.getNumeroFc();
//        if (clientes != null && !clientes.isEmpty()) {
//            LibraryLoader.loadJacobLibrary();
//            wsaa = new ActiveXComponent("WSAA");
//            System.out.println(Dispatch.get(wsaa, "InstallDir").toString()
//                    + " "
//                    + Dispatch.get(wsaa, "Version").toString()
//            );
//            Calendar cal = Calendar.getInstance();
//            fecha = cal.getTime();
//            hora = cal.get(Calendar.HOUR_OF_DAY);
//            minutos = cal.get(Calendar.MINUTE);
//            segundos = cal.get(Calendar.SECOND);
//            try {
//                tkt = new TicketTimeService().getTicketById(1L);
//            } catch (Exception ex) {
//                Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                return;
//            }
//            solicitarNuevoTicket();
//            for (Cliente cli : clientes) {
//                if (cli.getActivo()) {
//                    if (cli.getAbono() != null) {
//                        if (!cli.getGenerado()) {
//                            Factura fc = new Factura();
//                            // presentacion web
//                            try {
//                                LibraryLoader.loadJacobLibrary();
//                                wsaa = new ActiveXComponent("WSAA");
//                                System.out.println(Dispatch.get(wsaa, "InstallDir").toString()
//                                        + " "
//                                        + Dispatch.get(wsaa, "Version").toString()
//                                );
//                                cal = Calendar.getInstance();
//                                fecha = cal.getTime();
//                                hora = cal.get(Calendar.HOUR_OF_DAY);
//                                minutos = cal.get(Calendar.MINUTE);
//                                segundos = cal.get(Calendar.SECOND);
//                                tkt = new TicketTimeService().getTicketById(1L);
//                                if (fecha != tkt.getFecha()) {
//                                    solicitarNuevoTicket();
//                                } else if (hora != tkt.getHora()) {
//                                    if (hora == tkt.getHora() + 1) {
//                                        if (minutos > tkt.getMinuto()) {
//                                            solicitarNuevoTicket();
//                                        } else {
//                                            int xMinuto = 60 - tkt.getMinuto();
//                                            if ((xMinuto + minutos) > 30) {
//                                                solicitarNuevoTicket();
//                                            }
//                                        }
//                                    } else {
//                                        solicitarNuevoTicket();
//                                    }
//                                } else if (minutos - tkt.getMinuto() > 30) {
//                                    solicitarNuevoTicket();
//                                }
//                                ActiveXComponent wsfev1 = new ActiveXComponent("WSFEv1");
//                                Dispatch.put(wsfev1, "Cuit", new Variant("20142553202"));
//                                Dispatch.put(wsfev1, "Token", new Variant(token));
//                                Dispatch.put(wsfev1, "Sign", new Variant(sign));
//                                String cache = "";
//                                wsdl = "https://servicios1.afip.gov.ar/wsfev1/service.asmx?WSDL";
//                                Dispatch.call(wsfev1, "Conectar",
//                                        new Variant(cache),
//                                        new Variant(wsdl)
//                                );
//                                String tipo_cbte = "11";
//                                tipoComprob = tipo_cbte;
//                                String pto_vta = "6"; // Sucursal declarada WS
//                                sucursalFacturaPapel = "0006";
//                                Variant ult = Dispatch.call(wsfev1, "CompUltimoAutorizado",
//                                        new Variant(tipo_cbte),
//                                        new Variant(pto_vta));
//                                excepcion = Dispatch.get(wsfev1, "Excepcion").toString();
//                                System.out.println(wsfev1);
//                                //JOptionPane.showMessageDialog(this, "Ult.Comprb." + ult.toString());
//                                System.out.println("Ult.Comprb." + ult.toString());
//                                comprobanteNumero = Integer.parseInt(ult.toString());
//                                //JOptionPane.showMessageDialog(this, "Verificar");
//                                if (numf != comprobanteNumero) {
//                                    JOptionPane.showMessageDialog(this, "No coinciden los numeros");
//                                    return;
//                                }
//                                numf += 1;
//                                comprobanteNumero += 1;
//                                String fechaWs = new SimpleDateFormat("yyyyMMdd").format(sdf.parse(fechaTxt.getText()));
//                                String concepto = "1";// producto 
//                                String cui = cli.getCuit();
//                                String cuit1 = cui.substring(0, 2) + cui.substring(3, 11) + cui.substring(12, 13);
//                                String tipoD = String.valueOf(cli.getTipoDoc());
//                                String tipo_doc = tipoD, nro_doc = cuit1; //tipo y numero
//                                int cbte_nro = Integer.parseInt(ult.toString()) + 1,
//                                        cbt_desde = cbte_nro,
//                                        cbt_hasta = cbte_nro;
//                                numeroFacturaPapel = String.valueOf(cbte_nro);
//                                int largo = ("00000000" + numeroFacturaPapel).length();
//                                numeroFacturaPapel = ("00000000" + numeroFacturaPapel).substring(largo - 8, largo);
//                                Double importeAbono = cli.getAbono().getImporte();
//                                String imp_total = df.format(importeAbono).toString().replaceAll("\\,", "\\.");//"124.00";
//                                String imp_tot_conc = "0";
//                                String imp_neto = df.format(importeAbono).toString().replaceAll("\\,", "\\.");
//                                String imp_iva = "0";
//                                //int internos = 0;
//                                String imp_trib = "0", imp_op_ex = "0";
//                                String fecha_cbte = fechaWs, fecha_venc_pago = "";
//                                //String fecha_cbte = "20190531", fecha_venc_pago = "";
//                                String fecha_serv_desde = "", fecha_serv_hasta = "";
//                                String moneda_id = "PES", moneda_ctz = "1.000";
//                                Variant ok = Dispatch.call(wsfev1, "CrearFactura",
//                                        new Variant(concepto), new Variant(tipo_doc),
//                                        new Variant(nro_doc), new Variant(tipo_cbte),
//                                        new Variant(pto_vta),
//                                        new Variant(cbt_desde), new Variant(cbt_hasta),
//                                        new Variant(imp_total), new Variant(imp_tot_conc),
//                                        new Variant(imp_neto), new Variant(imp_iva),
//                                        new Variant(imp_trib), new Variant(imp_op_ex),
//                                        new Variant(fecha_cbte), new Variant(fecha_venc_pago),
//                                        new Variant(fecha_serv_desde), new Variant(fecha_serv_hasta),
//                                        new Variant(moneda_id), new Variant(moneda_ctz));
//                                Dispatch.put(wsfev1, "Reprocesar", new Variant(false));
//                                Variant cae = Dispatch.call(wsfev1, "CAESolicitar");
//                                String requ = Dispatch.get(wsfev1, "XmlRequest").toString();
//                                String resp = Dispatch.get(wsfev1, "XmlResponse").toString();
//                                excepcion = Dispatch.get(wsfev1, "Excepcion").toString();
//                                String errmsg = Dispatch.get(wsfev1, "ErrMsg").toString();
//                                String obs = Dispatch.get(wsfev1, "Obs").toString();
//                                String vto = Dispatch.get(wsfev1, "Vencimiento").toString();
//                                String resultado = Dispatch.get(wsfev1, "Resultado").toString();
//                                if (!resultado.equals("A")) {
//                                    JOptionPane.showMessageDialog(this, "Obs: " + obs + "\nError: " + errmsg);
//                                    return;
//                                }
//                                if (vto != "" && vto != null) {
//                                    vencCae = vto.substring(6, 8) + "/" + vto.substring(4, 6) + "/" + vto.substring(0, 4);
//                                }
//                                numCae = cae.toString();
//                                String ruta1 = "c:/abonos/xml/" + tipoComprob
//                                        + letraFacturaPapel + sucursalFacturaPapel
//                                        + numeroFacturaPapel + ".xm1";
//                                String ruta2 = "c:/abonos/xml/" + tipoComprob
//                                        + letraFacturaPapel + sucursalFacturaPapel
//                                        + numeroFacturaPapel + ".xm2";
//                                File archivo1 = new File(ruta1);
//                                File archivo2 = new File(ruta2);
//                                BufferedWriter bw1, bw2;
//                                bw1 = new BufferedWriter(new FileWriter(archivo1));
//                                bw2 = new BufferedWriter(new FileWriter(archivo2));
//                                bw1.write(requ);
//                                bw2.write(resp);
//                                bw1.close();
//                                bw2.close();
//                                int x = 0;
//                                Integer suma1 = 0;
//                                Integer suma2 = 0;
//                                String cadena = cuit1 + "0" + tipo_cbte + "0006" + cae + vto;
//                                for (int i = 0; i < 39; i++) {
//                                    if (x == 0) {
//                                        int num = Integer.valueOf(cadena.substring(i, i + 1).toString());
//                                        suma1 += num;
//                                        x = 1;
//                                    } else {
//                                        int num = Integer.valueOf(cadena.substring(i, i + 1).toString());
//                                        suma2 += num;
//                                        x = 0;
//                                    }
//                                }
//                                suma1 = suma1 * 3;
//                                int total = suma1 + suma2;
//                                int dv = (int) (rint(total / 10 + .9) * 10);
//                                dv = dv - total;
//                                cadena += String.valueOf(dv);
//
//                                cli.setGenerado(true);
//                                new ClienteService().updateCliente(cli);
//                            } catch (Exception e) {
//                                JOptionPane.showMessageDialog(this, e);
//                                e.printStackTrace();
//                                return;
//                            }
//
//                            // fin presentacion web
//                            try {
//                                fc.setFecha(sdf.parse(fechaTxt.getText()));
//                            } catch (ParseException ex) {
//                                Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                            }
//                            fc.setCae(Long.valueOf(numCae));
//                            fc.setCliente(cli);
//                            fc.setTipoDoc(11);
//                            try {
//                                fc.setFechaVencimCae(sdf.parse(vencCae));
//                            } catch (ParseException ex) {
//                                Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                            }
//                            fc.setImporte(cli.getAbono().getImporte());
//                            fc.setNumero(comprobanteNumero);
//                            fc.setSucursal(suc);
//                            
//                            try {
//                                
//                                fc = new FacturaService().saveFactura(fc);
//                            } catch (Exception ex) {
//                                Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                            }
//                            try {
//                                config = new ConfiguracionService().getConfiguracionById(id);
//                            } catch (Exception ex) {
//                                Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                            }
//                            config.setNumeroFc(numf);
//                            try {
//                                config = new ConfiguracionService().updateConfiguracion(config);
//                            } catch (Exception ex) {
//                                Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                            }
//                            Abono abono = fc.getCliente().getAbono();
//                            List<RenglonRubro> renglones = null;
//                            try {
//                                renglones = new RenglonAbonoService().getRenglonAbonosByAbono(abono);
//                            } catch (Exception ex) {
//                                Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                            }
//                            if(renglones != null && !renglones.isEmpty()){
//                                for(RenglonRubro ra:renglones){
//                                    RenglonFactura rf = new RenglonFactura();
//                                    rf.setFactura(fc);
//                                    rf.setImporte(ra.getImporte());
//                                    rf.setOrden(ra.getOrden());
//                                    rf.setTexto(ra.getTexto());
//                                    try {
//                                        new RenglonFacturaService().saveRenglonFactura(rf);
//                                    } catch (Exception ex) {
//                                        Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                                    }
//                                }
//                            }
//                        }
//                    }
//                }
//            }
//            volver();
//        }
//    }
    private void solicitarNuevoTicket() {
        LibraryLoader.loadJacobLibrary();
        ActiveXComponent wsaa = new ActiveXComponent("WSAA");
        String wsdl = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
        String userdir = "c:/certifmario";
        Dispatch.call(wsaa, "Autenticar",
                new Variant("wsfe"),
                new Variant(userdir + "/MARIO2020_484132ab2d5e5665.crt"),
                new Variant(userdir + "/clave_privada_20142553202_202010295426.key"),
                /*
                new Variant(userdir + "/nuevo2018_6851c538ff621621.crt"),
                new Variant(userdir + "/clave_privada_20142553202_201811010137.key"),
                 */
                new Variant(wsdl));
        excepcion = Dispatch.get(wsaa, "Excepcion").toString();
        token = Dispatch.get(wsaa, "Token").toString();
        sign = Dispatch.get(wsaa, "Sign").toString();
//        System.out.println(token);
//        System.out.println(sign);
//        JOptionPane.showMessageDialog(this, "ver");
        tkt.setFecha(fecha);
        tkt.setHora(hora);
        tkt.setMinuto(minutos);
        tkt.setSegundo(segundos);
//        tkt.setSign(sign);
//        tkt.setToken(token);
        try {
            new TicketTimeService().updateTicket(tkt);
        } catch (Exception ex) {
            Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No se pudo guardar nuevo Ticket");
        }
    }

    private void calcularFechas() {
//        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fe1, fe2, fe3, fe4;
        try {
            fe1 = sdf.parse(fechaTxt.getText());
            fe2 = UtilFrame.getFecha1Abono(fe1);
            fecha1Txt.setText(sdf.format(fe2));
            fe3 = UtilFrame.getFecha2Abono(fe1);
            fecha2Txt.setText(sdf.format(fe3));
            fe4 = UtilFrame.getFecha2Abono(fe1);
            fecha3Txt.setText(sdf.format(fe4));
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void llenarCombo() {
        combo.removeAllItems();
        combo.addItem("");
        rubros = null;
        try {
            rubros = new RubroService().getAllRubrosActivos();
        } catch (Exception ex) {
            Logger.getLogger(GenerarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (rubros != null && !rubros.isEmpty()) {
            for (Rubro ru : rubros) {
                combo.addItem(ru.getDetalle());
            }
        }
        comboP.removeAllItems();
        comboP.addItem("");
        comboP.addItem("1. PRODUCTO");
        comboP.addItem("2. SERVICIO");
        comboP.addItem("3. PRODUCTO/SERVICIO");
        comboP.setSelectedIndex(3);
    }
}
