/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.TextoPredefinido;
import ar.com.ventas.entities.TextoPredefinidoLinea;
import ar.com.ventas.services.TextoPredefinidoLineaService;
import ar.com.ventas.services.TextoPredefinidoService;
import ar.com.ventas.utils.UtilFrame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class ModificarTextoFrame extends javax.swing.JFrame {

    private TextoPredefinido tp;
    private List<TextoPredefinidoLinea> textos;

    /**
     * Creates new form ModificarTextoFrame
     */
    public ModificarTextoFrame(TextoPredefinido tp) {
        initComponents();
        this.tp = tp;
        cargarTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoCortoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        agregarLineaBtn = new javax.swing.JButton();
        borrarLineaBtn = new javax.swing.JButton();
        grabarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Texto Predefinido:");

        textoCortoTxt.setText("TEXTO CORTO");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEXTO"
            }
        ));
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        agregarLineaBtn.setText("Agregar Línea");
        agregarLineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLineaBtnActionPerformed(evt);
            }
        });

        borrarLineaBtn.setText("Borrar Línea");
        borrarLineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarLineaBtnActionPerformed(evt);
            }
        });

        grabarBtn.setText("Grabar");
        grabarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(grabarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(agregarLineaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(borrarLineaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textoCortoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 269, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoCortoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(agregarLineaBtn)
                    .addComponent(borrarLineaBtn)
                    .addComponent(grabarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void grabarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBtnActionPerformed
        grabar();
    }//GEN-LAST:event_grabarBtnActionPerformed

    private void agregarLineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLineaBtnActionPerformed
        agregarLinea();
    }//GEN-LAST:event_agregarLineaBtnActionPerformed

    private void borrarLineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarLineaBtnActionPerformed
        int row = tabla.getSelectedRow();
        borrarLinea(row);
    }//GEN-LAST:event_borrarLineaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTextoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTextoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTextoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTextoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTextoFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarLineaBtn;
    private javax.swing.JButton borrarLineaBtn;
    private javax.swing.JButton grabarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textoCortoTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        TextosPredefinidosAbmFrame mf = new TextosPredefinidosAbmFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void cargarTexto() {
        textoCortoTxt.setText(tp.getTextoCorto());
        textos = null;
        try {
            textos = new TextoPredefinidoLineaService().getAllTextoPredefinidoActivosByTextoPredefinido(tp);
        } catch (Exception ex) {
            Logger.getLogger(ModificarTextoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(textos != null && !textos.isEmpty()){
            UtilFrame.limpiarTabla(tabla);
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            for(TextoPredefinidoLinea tpl:textos){
                Object o[]=new Object[1];
                o[0]=tpl.getLinea();
//                o[1]=tpl.getOrden();
                tbl.addRow(o);
            }
            tabla.setModel(tbl);
        }
    }

    private void grabar() {
        if(validar()){
            for(TextoPredefinidoLinea tpl:textos){
                try {
                    new TextoPredefinidoLineaService().deleteTextoPredefinido(tpl);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarTextoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            int rows = tabla.getRowCount();
            tp.setTextoCorto(textoCortoTxt.getText());
            try {
                tp = new TextoPredefinidoService().updateTextoPredefinidoActivo(tp);
            } catch (Exception ex) {
                Logger.getLogger(ModificarTextoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int i = 0;i < rows;i++){
                TextoPredefinidoLinea tp0 = new TextoPredefinidoLinea();
                tp0.setOrden(i);
                tp0.setTextoPredefinido(tp);
                tp0.setLinea(tabla.getValueAt(i, 0).toString());
                try {
                    new TextoPredefinidoLineaService().saveTextoPredefinido(tp0);
                } catch (Exception ex) {
                    Logger.getLogger(ModificarTextoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void agregarLinea() {
        tabla = UtilFrame.agregarLinea(tabla, 1);
    }

    private void borrarLinea(int row) {
        tabla = UtilFrame.borrarLinea(tabla, row);
    }

    private boolean validar() {
        return true;
    }
}
