/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Abono;
import ar.com.ventas.entities.Cliente;
import ar.com.ventas.entities.Direccion;
import ar.com.ventas.entities.RenglonAbono;
import ar.com.ventas.entities.RenglonRubro;
import ar.com.ventas.entities.Rubro;
import ar.com.ventas.entities.TextoPredefinido;
import ar.com.ventas.entities.TextoPredefinidoLinea;
import ar.com.ventas.services.AbonoService;
import ar.com.ventas.services.ClienteService;
import ar.com.ventas.services.RenglonAbonoService;
import ar.com.ventas.services.RubroService;
import ar.com.ventas.services.TextoPredefinidoLineaService;
import ar.com.ventas.services.TextoPredefinidoService;
import ar.com.ventas.utils.UtilFrame;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class ModificarAbonoFrame extends javax.swing.JFrame {

    private Abono abono;
    private int orden = 0;
    private DecimalFormat df = new DecimalFormat("#0.00");
    private List<Cliente> clientes;
    private List<Rubro> rubros;
    private List<RenglonAbono> renglones;
    private List<TextoPredefinido> textos;
    private List<TextoPredefinidoLinea> lineaTextos;
    private List<RenglonAbono> renglones2;

    /**
     * Creates new form NuevoAbonoFrame
     *
     * @param abono
     */
    public ModificarAbonoFrame(Abono abono) {
        initComponents();
        this.abono = abono;
        limpiarCampos();
        llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        activoChk = new javax.swing.JCheckBox();
        grabarBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboC = new javax.swing.JComboBox<>();
        comboR = new javax.swing.JComboBox<>();
        importeTxt = new javax.swing.JTextField();
        calcularBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        comboT = new javax.swing.JComboBox<>();
        agregarLineaBtn = new javax.swing.JButton();
        eliminarLineaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICACION DETALLES DE ABONO");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        codigoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoTxt.setText("CODIGO");

        activoChk.setText("Activo");

        grabarBtn.setText("Grabar");
        grabarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("CLIENTE:");

        jLabel3.setText("RUBRO:");

        jLabel4.setText("IMPORTE:");

        comboC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        importeTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        importeTxt.setText("IMPORTE");

        calcularBtn.setText("Calcular");
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DETALLE", "IMPORTE"
            }
        ));
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(300);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        jLabel5.setText("TEXTO PREDEFINIDO:");

        comboT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTActionPerformed(evt);
            }
        });

        agregarLineaBtn.setText("Agregar Línea");
        agregarLineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLineaBtnActionPerformed(evt);
            }
        });

        eliminarLineaBtn.setText("Eliminar Línea");
        eliminarLineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLineaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grabarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(calcularBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(comboC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(activoChk)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(comboR, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarLineaBtn)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarLineaBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activoChk)
                    .addComponent(jLabel5)
                    .addComponent(comboT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarLineaBtn)
                    .addComponent(eliminarLineaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grabarBtn)
                    .addComponent(volverBtn)
                    .addComponent(jLabel4)
                    .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void grabarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBtnActionPerformed
        grabar();
    }//GEN-LAST:event_grabarBtnActionPerformed

    private void comboTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTActionPerformed
        int row = comboT.getSelectedIndex();
        if (row > 0) {
            int a = JOptionPane.showConfirmDialog(this, "DESEA INCORPORAR EL TEXTO AL ABONO?",
                    "Atención", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                cargarTexto(row - 1);
            }
        }
    }//GEN-LAST:event_comboTActionPerformed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        calcular();
    }//GEN-LAST:event_calcularBtnActionPerformed

    private void agregarLineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLineaBtnActionPerformed
        tabla = UtilFrame.agregarLinea(tabla, 2);
    }//GEN-LAST:event_agregarLineaBtnActionPerformed

    private void eliminarLineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLineaBtnActionPerformed
        int row = tabla.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "ELEGIR");
            return;
        }
        tabla = UtilFrame.borrarLinea(tabla, row);
    }//GEN-LAST:event_eliminarLineaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarAbonoFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activoChk;
    private javax.swing.JButton agregarLineaBtn;
    private javax.swing.JButton calcularBtn;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JComboBox<String> comboC;
    private javax.swing.JComboBox<String> comboR;
    private javax.swing.JComboBox<String> comboT;
    private javax.swing.JButton eliminarLineaBtn;
    private javax.swing.JButton grabarBtn;
    private javax.swing.JTextField importeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        AbmAbonoFrame mf = new AbmAbonoFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void limpiarCampos() {
        codigoTxt.setText("");
        activoChk.setSelected(true);
        comboT.removeAllItems();
        comboT.addItem("");
        textos = null;
        try {
            textos = new TextoPredefinidoService().getAllTextoPredefinidoActivos();
        } catch (Exception ex) {
            Logger.getLogger(ModificarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (textos != null && !textos.isEmpty()) {
            for (TextoPredefinido tp : textos) {
                comboT.addItem(tp.getTextoCorto());
            }
        }
    }

    private void grabar() {
        if (verificar()) {
            int rowC = comboC.getSelectedIndex();
            int rowR = comboR.getSelectedIndex();
            Rubro ru = rubros.get(rowR - 1);
            Cliente cl = clientes.get(rowC - 1);
            abono.setCodigo(Integer.valueOf(codigoTxt.getText()));
            if (activoChk.isSelected()) {
                abono.setActivo(true);
            } else {
                abono.setActivo(false);
            }
            abono.setGenerado(true);
            abono.setImporte(Double.valueOf(importeTxt.getText().replace(",", ".")));
            abono.setRubro(ru);
            abono.setCliente(cl);
            renglones = new ArrayList<>();
            int rowT = tabla.getRowCount();
            for(int i = 0;i<rowT;i++){
                RenglonAbono ra = new RenglonAbono();
                ra.setAbono(abono);
                Double importe;
                String str1 = tabla.getValueAt(i, 0).toString();
                String str = tabla.getValueAt(i, 1).toString();
                if(str.isEmpty()){
                    importe = 0.0;
                }else{
                    importe = Double.valueOf(str.replace(",", "."));
                }
                ra.setImporte(importe);
                ra.setOrden(i);
                ra.setTexto(str1);
                renglones.add(ra);
            }
            try {
                new AbonoService().updateAbonoCompleto(abono, renglones, renglones2);
            } catch (Exception ex) {
                Logger.getLogger(ModificarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR GRABANDO");
            }
            JOptionPane.showMessageDialog(this, "GRABADO OK");
            volver();
        }
    }

    private boolean verificar() {
        return true;
    }

    private void llenarCampos() {
        codigoTxt.setText(abono.getCodigo().toString());
        if (abono.getActivo() != null) {
            if (abono.getActivo()) {
                activoChk.setSelected(true);
            } else {
                activoChk.setSelected(false);
            }
        } else {
            activoChk.setSelected(false);
        }
        importeTxt.setText(df.format(abono.getImporte()));
        rubros = null;
        clientes = null;
        try {
            rubros = new RubroService().getAllRubrosActivos();
        } catch (Exception ex) {
            Logger.getLogger(ModificarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            clientes = new ClienteService().getAllClientes();
        } catch (Exception ex) {
            Logger.getLogger(ModificarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        comboC.removeAllItems();
        comboR.removeAllItems();
        comboC.addItem("");
        comboR.addItem("");
        Long idC = abono.getCliente().getId();
        Long idR = abono.getRubro().getId();
        int posC = 0;
        int pC = 0;
        int posR = 0;
        int pR = 0;
        if (clientes != null && !clientes.isEmpty()) {
            for (Cliente c : clientes) {
                posC += 1;
                Direccion dm = c.getDireccion();
                comboC.addItem(dm.getCalle() + " " + dm.getNumero());
                if (idC.equals(c.getId())) {
                    pC = posC;
                }
            }
        }
        if (rubros != null && !rubros.isEmpty()) {
            for (Rubro r : rubros) {
                posR += 1;
                comboR.addItem(r.getDetalle());
                if (idR.equals(r.getId())) {
                    pR = posR;
                }
            }
        }
        comboC.setSelectedIndex(pC);
        comboR.setSelectedIndex(pR);
        UtilFrame.limpiarTabla(tabla);
        renglones = null;
        try {
            renglones = new RenglonAbonoService().getRenglonAbonosByAbono(abono);
        } catch (Exception ex) {
            Logger.getLogger(ModificarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        renglones2 = renglones;
        System.out.println(renglones);
        System.out.println(renglones2);
        if (renglones != null && !renglones.isEmpty()) {
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            for (RenglonAbono re : renglones) {
                Object o[] = new Object[2];
                o[0] = re.getTexto();
                if (re.getImporte() != null) {
                    if (re.getImporte() > 0.009) {
                        o[1] = df.format(re.getImporte());
                    } else {
                        o[1] = "";
                    }
                } else {
                    o[1] = "";
                }
                tbl.addRow(o);
            }
            tabla.setModel(tbl);
        }
    }

    private void cargarTexto(int i) {
        TextoPredefinido tp1 = textos.get(i);
        lineaTextos = null;
        try {
            lineaTextos = new TextoPredefinidoLineaService().getAllTextoPredefinidoActivosByTextoPredefinido(tp1);
        } catch (Exception ex) {
            Logger.getLogger(ModificarAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
//        if(renglones == null){
//            renglones = new ArrayList<>();
//        }
        if (lineaTextos != null && !lineaTextos.isEmpty()) {
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            for (TextoPredefinidoLinea textoLinea : lineaTextos) {
                Object o[] = new Object[2];
                o[0] = textoLinea.getLinea();
                o[1] = "";
                tbl.addRow(o);
            }
            tabla.setModel(tbl);
        }
    }

    private void calcular() {
        int rows = tabla.getRowCount();
        Double total = 0.0;
        for (int i = 0; i < rows; i++) {
            String imp1 = tabla.getValueAt(i, 1).toString();
            if (!imp1.isEmpty()) {
                Double parcial = Double.valueOf(imp1.replace(",", "."));
                total += parcial;
            }
            importeTxt.setText(df.format(total));
        }
    }
}
