/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Direccion;
import ar.com.ventas.entities.TitularCuit;
import ar.com.ventas.estructuras.Categoria;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.services.TitularCuitService;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class NuevoTitularCuitFrame extends javax.swing.JFrame {

    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private DecimalFormat df = new DecimalFormat("#0.00");
    private Integer o = 0;
    private List<Categoria> categorias = new ArrayList<>();

    /**
     * Creates new form TitularCuitFrame
     */
    public NuevoTitularCuitFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
//        setExtendedState(this.MAXIMIZED_BOTH);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionesTxt = new javax.swing.JTextArea();
        guardarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        razonSocialTxt = new javax.swing.JTextField();
        calleTxt = new javax.swing.JTextField();
        localidadTxt = new javax.swing.JTextField();
        provinciaTxt = new javax.swing.JTextField();
        cuitTxt = new javax.swing.JTextField();
        iibbTxt = new javax.swing.JTextField();
        fechaInicioActividadesTxt = new javax.swing.JTextField();
        sucursalTxt = new javax.swing.JTextField();
        telefonoTxt = new javax.swing.JTextField();
        mailTxt = new javax.swing.JTextField();
        comboM = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        activoChk = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR TITULAR DE CUIT");

        jLabel2.setText("Razon Social:");

        jLabel3.setText("Domicilio Fiscal Calle y Número:");

        jLabel7.setText("CP - Localidad:");

        jLabel8.setText("Provincia:");

        jLabel9.setText("CUIT:");

        jLabel10.setText("IIBB:");

        jLabel11.setText("Fecha Inicio Actividades:");

        jLabel13.setText("Categoría:");

        jLabel14.setText("Sucursal:");

        jLabel16.setText("Teléfono:");

        jLabel17.setText("Mail:");

        jLabel18.setText("Observaciones:");

        observacionesTxt.setColumns(20);
        observacionesTxt.setRows(5);
        jScrollPane1.setViewportView(observacionesTxt);

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        razonSocialTxt.setText("RAZON SOCIAL");

        calleTxt.setText("DOMICILIO CALLE Y NUMERO");

        localidadTxt.setText("CP LOCALIDAD");

        provinciaTxt.setText("PROVINCIA");

        cuitTxt.setText("CUIT");

        iibbTxt.setText("IIBB");

        fechaInicioActividadesTxt.setText("FECHA INICIO ACT");

        sucursalTxt.setText("SUCURSAL");

        telefonoTxt.setText("TELEFONO");

        mailTxt.setText("MAIL");

        comboM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMActionPerformed(evt);
            }
        });
        comboM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboMKeyPressed(evt);
            }
        });

        jLabel19.setText("*");

        jLabel21.setText("*");

        jLabel22.setText("*");

        jLabel23.setText("*");

        jLabel24.setText("*");

        jLabel26.setText("*");

        jLabel27.setText("*");

        jLabel28.setText("*");

        jLabel29.setText("*");

        activoChk.setText("Activo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechaInicioActividadesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboM, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sucursalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(telefonoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                            .addComponent(mailTxt))
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21)))
                                .addGap(59, 59, 59)
                                .addComponent(activoChk))
                            .addComponent(jLabel18))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volverBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(iibbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel27))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(localidadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                                    .addComponent(provinciaTxt)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel23)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel24))))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 628, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(activoChk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(localidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(provinciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(iibbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fechaInicioActividadesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sucursalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void comboMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMActionPerformed
//        if (evt.getModifiers() == 16) {
//            int row = comboM.getSelectedIndex();
//            if (row > 0) {
//                cargarImporte();
//            }
//        }
    }//GEN-LAST:event_comboMActionPerformed

    private void comboMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboMKeyPressed
//        if (evt.getKeyCode() == 10) {
//            int row = comboM.getSelectedIndex();
//            if (row > 0) {
//                cargarImporte();
//            }
//        }
    }//GEN-LAST:event_comboMKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTitularCuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTitularCuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTitularCuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTitularCuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoTitularCuitFrame().setVisible(true);
            }
        });
    }

    private void limpiarCampos() {
        llenarCombos();
        activoChk.setVisible(true);
        activoChk.setSelected(true);
        razonSocialTxt.setText("");
        razonSocialTxt.requestFocus();
        calleTxt.setText("");
        localidadTxt.setText("");
        provinciaTxt.setText("");
        cuitTxt.setText("");
        iibbTxt.setText("");
        fechaInicioActividadesTxt.setText(sdf.format(new Date()));
        comboM.setSelectedIndex(6);
        sucursalTxt.setText("");
        telefonoTxt.setText("");
        mailTxt.setText("");
        observacionesTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activoChk;
    private javax.swing.JTextField calleTxt;
    private javax.swing.JComboBox<String> comboM;
    private javax.swing.JTextField cuitTxt;
    private javax.swing.JTextField fechaInicioActividadesTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField iibbTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localidadTxt;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextArea observacionesTxt;
    private javax.swing.JTextField provinciaTxt;
    private javax.swing.JTextField razonSocialTxt;
    private javax.swing.JTextField sucursalTxt;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        AbmTitularCuitFrame apf = new AbmTitularCuitFrame();
        apf.setVisible(true);
        this.dispose();
    }

    private void llenarCombos() {
        comboM.removeAllItems();
        comboM.addItem("");
        for (Categoria cate : Categoria.values()) {
            comboM.addItem(cate.getDetalle());
            categorias.add(cate);
        }
    }

    private void guardar() {
        if (validar()) {
            Boolean activo;
            if (activoChk.isSelected()) {
                activo = true;
            } else {
                activo = false;
            }
            TitularCuit titular = new TitularCuit();
            titular.setCalleNumero(calleTxt.getText());
            titular.setCodigoPostalLocalidad(localidadTxt.getText());
            titular.setProvincia(provinciaTxt.getText());
            titular.setActivo(activo);
            int row = comboM.getSelectedIndex();
            titular.setCuit(cuitTxt.getText());
            Date fecha1 = new Date();
            try {
                fecha1 = sdf.parse(fechaInicioActividadesTxt.getText());
            } catch (ParseException ex) {
                Logger.getLogger(NuevoTitularCuitFrame.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            titular.setFechaInicioActividades(fecha1);
            titular.setIibb(iibbTxt.getText());
            titular.setMail(mailTxt.getText());
            titular.setRazonSocial(razonSocialTxt.getText());
            titular.setObservaciones(observacionesTxt.getText());
            int sucursal = Integer.valueOf(sucursalTxt.getText());
            titular.setSucursal(sucursal);
            titular.setTelefono(telefonoTxt.getText());
            titular.setCategoria(categorias.get(row -1).getCodigo());
            try {
                new TitularCuitService().saveTitular(titular);
            } catch (Exception ex) {
                Logger.getLogger(NuevoTitularCuitFrame.class
                        .getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR GUARDANDO TITULAR");
            }
            JOptionPane.showMessageDialog(this, "TITULAR GUARDADO CORRECTAMENTE");
            volver();
        }
    }

    private boolean validar() {
        int rowM = comboM.getSelectedIndex();
        if (rowM < 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA CATEGORIA MONOTRIBUTO");
            comboM.requestFocus();
            return false;
        }

        if (razonSocialTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR UN NOMBRE\n"
                    + "PARA RAZON SOCIAL TITULAR");
            razonSocialTxt.requestFocus();
            return false;
        }
        if (calleTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR LA CALLE DEL TITULAR DE CUIT\n"
                    + "O UTILICE LA MISMA CALLE DE LA PERSONA");
            calleTxt.requestFocus();
            return false;
        }

        if (localidadTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR LOCALIDAD DE DIRECCION DEL TITULAR DE CUIT");
            localidadTxt.requestFocus();
            return false;
        }
        if (provinciaTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR PROVINCIA DE DIRECCION DEL TITULAR DE CUIT2");
            provinciaTxt.requestFocus();
            return false;
        }
        if (cuitTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR NUMERO DE CUIT\n"
                    + "O UTILICE EL CUIL DE LA PERSONA");
            cuitTxt.requestFocus();
            return false;
        }
        if (iibbTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR NUMERO DE INGRESOS BRUTOS\n"
                    + "O UTILICE EL MISMO NUMERO DE CUIT");
            iibbTxt.requestFocus();
            return false;
        }
        if (fechaInicioActividadesTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR UNA FECHA DE INICIO DE ACTIVIDADES");
            fechaInicioActividadesTxt.requestFocus();
            return false;
        }
        if (fechaInicioActividadesTxt.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "VERIFIQUE FECHA DE INICIO DE ACTIVIDADES");
            fechaInicioActividadesTxt.requestFocus();
            return false;
        }
        if (sucursalTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INDICAR UNA SUCURSAL O PUNTO DE VENTA DECLARADO EN AFIP");
            sucursalTxt.requestFocus();
            return false;
        }
        return true;
    }
}
