/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Abono;
import ar.com.ventas.entities.Cliente;
import ar.com.ventas.entities.Direccion;
import ar.com.ventas.entities.RenglonAbono;
import ar.com.ventas.entities.Rubro;
import ar.com.ventas.entities.TextoPredefinido;
import ar.com.ventas.entities.TextoPredefinidoLinea;
import ar.com.ventas.services.AbonoService;
import ar.com.ventas.services.ClienteService;
import ar.com.ventas.services.RubroService;
import ar.com.ventas.services.TextoPredefinidoLineaService;
import ar.com.ventas.services.TextoPredefinidoService;
import ar.com.ventas.utils.UtilFrame;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class NuevoAbonoFrame extends javax.swing.JFrame {

    private DecimalFormat df = new DecimalFormat("#0.00");
    private List<Cliente> clientes;
    private List<Rubro> rubros;
    private List<TextoPredefinido> textos;
    private List<RenglonAbono> renglones = new ArrayList<>();
    private Integer codigo;

    /**
     * Creates new form NuevoAbonoFrame
     */
    public NuevoAbonoFrame() {
        initComponents();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        grabarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboC = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboR = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        importeTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        calcularBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboT = new javax.swing.JComboBox<>();
        agregarLineaBtn = new javax.swing.JButton();
        eliminarLineaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("NUEVO ABONO");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        codigoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoTxt.setText("CODIGO");

        grabarBtn.setText("Grabar");
        grabarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente:");

        comboC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("RUBRO:");

        comboR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("IMPORTE:");

        importeTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        importeTxt.setText("IMPORTE");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEXTO", "IMPORTE"
            }
        ));
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(300);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(40);
        }

        calcularBtn.setText("Calcular");
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Texto Predeterminado:");

        comboT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTActionPerformed(evt);
            }
        });

        agregarLineaBtn.setText("Agregar Línea");
        agregarLineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLineaBtnActionPerformed(evt);
            }
        });

        eliminarLineaBtn.setText("Eliminar Línea");
        eliminarLineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLineaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(comboC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grabarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(comboR, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarLineaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarLineaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(calcularBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularBtn)
                    .addComponent(agregarLineaBtn)
                    .addComponent(eliminarLineaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grabarBtn)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void grabarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBtnActionPerformed
        grabar();
    }//GEN-LAST:event_grabarBtnActionPerformed

    private void agregarLineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLineaBtnActionPerformed
        tabla = UtilFrame.agregarLinea(tabla, 2);
    }//GEN-LAST:event_agregarLineaBtnActionPerformed

    private void eliminarLineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLineaBtnActionPerformed
        int row = tabla.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "ELEGIR");
            return;
        }
        tabla = UtilFrame.borrarLinea(tabla, row);
    }//GEN-LAST:event_eliminarLineaBtnActionPerformed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        calcular();
    }//GEN-LAST:event_calcularBtnActionPerformed

    private void comboTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTActionPerformed
        agregarTextoPredefinido();
    }//GEN-LAST:event_comboTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoAbonoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoAbonoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarLineaBtn;
    private javax.swing.JButton calcularBtn;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JComboBox<String> comboC;
    private javax.swing.JComboBox<String> comboR;
    private javax.swing.JComboBox<String> comboT;
    private javax.swing.JButton eliminarLineaBtn;
    private javax.swing.JButton grabarBtn;
    private javax.swing.JTextField importeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        AbmAbonoFrame mf = new AbmAbonoFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void limpiarCampos() {
        codigoTxt.setText("");
        importeTxt.setText("");
        tabla = UtilFrame.limpiarTabla(tabla);
        clientes = null;
        rubros = null;
        textos = null;
        comboC.removeAllItems();
        comboC.addItem("");
        comboR.removeAllItems();
        comboR.addItem("");
        comboT.removeAllItems();
        comboT.addItem("");
        try {
            clientes = new ClienteService().getAllClientes();
        } catch (Exception ex) {
            Logger.getLogger(NuevoAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (clientes != null && !clientes.isEmpty()) {
            for (Cliente c : clientes) {
                Direccion dm = c.getDireccion();
                comboC.addItem(dm.getCalle() + " " + dm.getNumero());
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HAY CLIENTES");
            volver();
        }
        try {
            rubros = new RubroService().getAllRubrosActivos();
        } catch (Exception ex) {
            Logger.getLogger(NuevoAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (rubros != null && !rubros.isEmpty()) {
            for (Rubro r : rubros) {
                comboR.addItem(r.getDetalle());
            }
        }
        try {
            textos = new TextoPredefinidoService().getAllTextoPredefinidoActivos();
        } catch (Exception ex) {
            Logger.getLogger(NuevoAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (textos != null && !textos.isEmpty()) {
            for (TextoPredefinido tp : textos) {
                comboT.addItem(tp.getTextoCorto());
            }
        }
        codigo = 0;
        int o = 0;
        try {
            codigo = new AbonoService().getCodigoSiguiente();
            if (codigo != null) {
                o = 1;
            } else {
                o = 0;
            }
        } catch (Exception ex) {
//            Logger.getLogger(NuevoRubroFrame.class.getName()).log(Level.SEVERE, null, ex);
            o = 0;
        }
        if (o == 0) {
            codigo = 0;
        }
        codigo += 1;
        codigoTxt.setText(codigo.toString());
        comboC.requestFocus();
    }

    private void grabar() {
        if (verificar()) {
            Abono abono = new Abono();
            int rowC = comboC.getSelectedIndex() - 1;
            int rowR = comboR.getSelectedIndex() - 1;
            if (rowC < 0) {
                return;
            }
            if (rowR < 0) {
                return;
            }
            Cliente cliente = clientes.get(rowC);
            Rubro rubro = rubros.get(rowR);
            abono.setCodigo(Integer.valueOf(codigoTxt.getText()));
            abono.setActivo(true);
            abono.setGenerado(true);
            abono.setCliente(cliente);
            abono.setRubro(rubro);
            abono.setImporte(Double.valueOf(importeTxt.getText().replace(",", ".")));
            renglones = new ArrayList<>();
            int rowT = tabla.getRowCount();
            for(int i = 0;i < rowT; i++){
                RenglonAbono ra = new RenglonAbono();
                ra.setAbono(abono);
                Double importe;
                String str1 = tabla.getValueAt(i, 0).toString();
                String str = tabla.getValueAt(i, 1).toString();
                if(str.isEmpty()){
                    importe = 0.0;
                }else{
                    importe = Double.valueOf(str.replace(",", "."));
                }
                ra.setImporte(importe);
                ra.setOrden(i);
                ra.setTexto(str1);
                renglones.add(ra);
            }
            System.out.println(abono);
            System.out.println(renglones);
            System.out.println(renglones.get(0).getAbono());
            try {
                new AbonoService().saveAbonoCompleto(abono, renglones);
            } catch (Exception ex) {
                Logger.getLogger(NuevoAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            volver();
        }
    }

    private boolean verificar() {
        int rowC = comboC.getSelectedIndex();
        int rowR = comboR.getSelectedIndex();
        int rowT = tabla.getRowCount();
        if (rowC < 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN CLIENTE");
            comboC.requestFocus();
            return false;
        }
        if (rowR < 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN RUBRO");
            comboR.requestFocus();
            return false;
        }
        if (importeTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE HABER CALCULADO UN IMPORTE");
            return false;
        }
        if(rowT < 1){
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UN TEXTO PARA EL ABONO");
            return false;
        }
        return true;
    }

    private void calcular() {
        int rows = tabla.getRowCount();
        Double total = 0.0;
        for (int i = 0; i < rows; i++) {
            String imp1 = tabla.getValueAt(i, 1).toString();
            if (!imp1.isEmpty()) {
                Double parcial = Double.valueOf(imp1);
                total += parcial;
            }
            importeTxt.setText(df.format(total));
        }
    }

    private void agregarTextoPredefinido() {
        int rowT = comboT.getSelectedIndex();
        if (rowT > 0) {
            TextoPredefinido tp = textos.get(rowT - 1);
            List<TextoPredefinidoLinea> lineas = null;
            try {
                lineas = new TextoPredefinidoLineaService().getAllTextoPredefinidoActivosByTextoPredefinido(tp);
            } catch (Exception ex) {
                Logger.getLogger(NuevoAbonoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            int cantidadLineas = lineas.size();
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            for (int i = 0; i < cantidadLineas; i++) {
                Object o[] = new Object[2];
                String texto = lineas.get(i).getLinea();
                o[0] = texto;
                o[1] = "";
                RenglonAbono ra = new RenglonAbono();
                ra.setOrden(i);
                ra.setTexto(texto);
                ra.setImporte(0.0);
                renglones.add(ra);
                tbl.addRow(o);
            }
            tabla.setModel(tbl);
        }
    }
}
