/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.CertificadosAfip;
import ar.com.ventas.entities.Configuracion;
import ar.com.ventas.entities.TicketTime;
import ar.com.ventas.entities.TicketToken;
import ar.com.ventas.entities.TitularCuit;
import ar.com.ventas.estructuras.Categoria;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.CertificadosAfipService;
import ar.com.ventas.services.ConfiguracionService;
import ar.com.ventas.services.TitularCuitService;
import ar.com.ventas.utils.UtilAfip;
import com.jacob.activeX.ActiveXComponent;
import com.jacob.com.Dispatch;
import com.jacob.com.LibraryLoader;
import com.jacob.com.Variant;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class TestAfipFrame extends javax.swing.JFrame {

    private DecimalFormat df = new DecimalFormat("#0");
    private List<Categoria> categorias = new ArrayList<>();
    private List<TitularCuit> titulares;
    private TitularCuit titu;
    private String categoria = "04";

    /**
     * Creates new form TestAfipFrame
     */
    public TestAfipFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        titularTxt = new javax.swing.JTextField();
        consultarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        fcAenDbTxt = new javax.swing.JTextField();
        ncAenDbTxt = new javax.swing.JTextField();
        fcBenDbTxt = new javax.swing.JTextField();
        ncBenDbTxt = new javax.swing.JTextField();
        fcCenDbTxt = new javax.swing.JTextField();
        ncCenDbTxt = new javax.swing.JTextField();
        fcAenAfipTxt = new javax.swing.JTextField();
        ncAenAfipTxt = new javax.swing.JTextField();
        fcBenAfipTxt = new javax.swing.JTextField();
        ncBenAfipTxt = new javax.swing.JTextField();
        fcCenAfipTxt = new javax.swing.JTextField();
        ncCenAfipTxt = new javax.swing.JTextField();
        fcAenDbLbl = new javax.swing.JLabel();
        ncAenDbLbl = new javax.swing.JLabel();
        fcBenDbLbl = new javax.swing.JLabel();
        ncBenDbLbl = new javax.swing.JLabel();
        fcCenDbLbl = new javax.swing.JLabel();
        ncCenDbLbl = new javax.swing.JLabel();
        fcAenAfipLbl = new javax.swing.JLabel();
        ncAenAfipLbl = new javax.swing.JLabel();
        fcBenAfipLbl = new javax.swing.JLabel();
        ncBenAfipLbl = new javax.swing.JLabel();
        fcCenAfipLbl = new javax.swing.JLabel();
        ncCenAfipLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cuitTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        categoriaTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CONSULTAR AFIP");

        jLabel4.setText("TITULAR: ");

        titularTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titularTxt.setText("TITULAR");

        consultarBtn.setText("Consultar");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });

        fcAenDbTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fcAenDbTxt.setText("ULT FC A EN DB");

        ncAenDbTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ncAenDbTxt.setText("ULT NC A EN DB");

        fcBenDbTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fcBenDbTxt.setText("ULT FC B EN DB");

        ncBenDbTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ncBenDbTxt.setText("ULT NC B EN DB");

        fcCenDbTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fcCenDbTxt.setText("ULT FC C EN DB");

        ncCenDbTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ncCenDbTxt.setText("ULT NC C EN DB");

        fcAenAfipTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fcAenAfipTxt.setText("ULT FC A EN AFIP");

        ncAenAfipTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ncAenAfipTxt.setText("ULT NC A EN AFIP");

        fcBenAfipTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fcBenAfipTxt.setText("ULT FC B EN AFIP");

        ncBenAfipTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ncBenAfipTxt.setText("ULT NC B EN AFIP");

        fcCenAfipTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fcCenAfipTxt.setText("ULT FC C EN AFIP");

        ncCenAfipTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ncCenAfipTxt.setText("ULT NC C EN AFIP");

        fcAenDbLbl.setText("Ultima FC A en Sistema:");

        ncAenDbLbl.setText("Ultima NC A en Sistema:");

        fcBenDbLbl.setText("Ultima FC B en Sistema:");

        ncBenDbLbl.setText("Ultima NC B en Sistema:");

        fcCenDbLbl.setText("Ultima FC C en Sistema:");

        ncCenDbLbl.setText("Ultima NC C en Sistema:");

        fcAenAfipLbl.setText("Ultima FC A en Afip:");

        ncAenAfipLbl.setText("Ultima NC A en Afip:");

        fcBenAfipLbl.setText("Ultima FC B en Afip:");

        ncBenAfipLbl.setText("Ultima NC B en Afip:");

        fcCenAfipLbl.setText("Ultima FC C en Afip:");

        ncCenAfipLbl.setText("Ultima NC C en Afip:");

        jLabel1.setText("CUIT PARA AFIP:");

        cuitTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cuitTxt.setText("CUIT");

        jLabel2.setText("Categoría:");

        categoriaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        categoriaTxt.setText("CATEGORIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titularTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fcAenDbLbl)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(fcAenDbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(categoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fcBenDbLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(fcBenDbTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ncBenDbLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ncBenDbTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fcCenDbLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(fcCenDbTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ncAenDbLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ncAenDbTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ncCenDbLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ncCenDbTxt)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ncAenAfipLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ncAenAfipTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fcBenAfipLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(fcBenAfipTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ncBenAfipLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ncBenAfipTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fcCenAfipLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(fcCenAfipTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ncCenAfipLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ncCenAfipTxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fcAenAfipLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(fcAenAfipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(titularTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(categoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fcAenDbLbl)
                    .addComponent(fcAenDbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcAenAfipLbl)
                    .addComponent(fcAenAfipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncAenDbLbl)
                    .addComponent(ncAenDbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncAenAfipLbl)
                    .addComponent(ncAenAfipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fcBenDbLbl)
                    .addComponent(fcBenDbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcBenAfipLbl)
                    .addComponent(fcBenAfipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncBenDbLbl)
                    .addComponent(ncBenDbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncBenAfipLbl)
                    .addComponent(ncBenAfipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fcCenDbLbl)
                    .addComponent(fcCenDbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcCenAfipLbl)
                    .addComponent(fcCenAfipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncCenDbLbl)
                    .addComponent(ncCenDbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncCenAfipLbl)
                    .addComponent(ncCenAfipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarBtn)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        consultar();
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        if (evt.getModifiers() == 16) {
            int row = combo.getSelectedIndex();
            if (row > 0) {
                mostrar(row - 1);
            }
        }
    }//GEN-LAST:event_comboActionPerformed

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed
        if (evt.getKeyCode() == 10) {
            int row = combo.getSelectedIndex();
            if (row > 0) {
                mostrar(row - 1);
            }
        }
    }//GEN-LAST:event_comboKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAfipFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoriaTxt;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JTextField cuitTxt;
    private javax.swing.JLabel fcAenAfipLbl;
    private javax.swing.JTextField fcAenAfipTxt;
    private javax.swing.JLabel fcAenDbLbl;
    private javax.swing.JTextField fcAenDbTxt;
    private javax.swing.JLabel fcBenAfipLbl;
    private javax.swing.JTextField fcBenAfipTxt;
    private javax.swing.JLabel fcBenDbLbl;
    private javax.swing.JTextField fcBenDbTxt;
    private javax.swing.JLabel fcCenAfipLbl;
    private javax.swing.JTextField fcCenAfipTxt;
    private javax.swing.JLabel fcCenDbLbl;
    private javax.swing.JTextField fcCenDbTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ncAenAfipLbl;
    private javax.swing.JTextField ncAenAfipTxt;
    private javax.swing.JLabel ncAenDbLbl;
    private javax.swing.JTextField ncAenDbTxt;
    private javax.swing.JLabel ncBenAfipLbl;
    private javax.swing.JTextField ncBenAfipTxt;
    private javax.swing.JLabel ncBenDbLbl;
    private javax.swing.JTextField ncBenDbTxt;
    private javax.swing.JLabel ncCenAfipLbl;
    private javax.swing.JTextField ncCenAfipTxt;
    private javax.swing.JLabel ncCenDbLbl;
    private javax.swing.JTextField ncCenDbTxt;
    private javax.swing.JTextField titularTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        String spc20 = "                    ";
        fcAenDbTxt.setText(spc20);
        ncAenDbTxt.setText(spc20);
        fcBenDbTxt.setText(spc20);
        ncBenDbTxt.setText(spc20);
        fcCenDbTxt.setText(spc20);
        ncCenDbTxt.setText(spc20);
        fcAenAfipTxt.setText(spc20);
        ncAenAfipTxt.setText(spc20);
        fcBenAfipTxt.setText(spc20);
        ncBenAfipTxt.setText(spc20);
        fcCenAfipTxt.setText(spc20);
        ncCenAfipTxt.setText(spc20);
        ocultar1();
        ocultar2();
        for (Categoria ca : Categoria.values()) {
            categorias.add(ca);
        }
        llenarCombo();
    }

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void consultar() {
        int nFcC_db = 0;
        int nNcC_db = 0;
        int nFcA_db = 0;
        int nNcA_db = 0;
        int nFcB_db = 0;
        int nNcB_db = 0;
        int nFcC_afip = 0;
        int nNcC_afip = 0;
        int nFcA_afip = 0;
        int nNcA_afip = 0;
        int nFcB_afip = 0;
        int nNcB_afip = 0;
        Configuracion config = null;
        CertificadosAfip ca = null;
        try {
            ca = new CertificadosAfipService().getCertificadoByTitular(titu);
        } catch (Exception ex) {
            Logger.getLogger(TestAfipFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            config = new ConfiguracionService().getConfiguracionByTitular(titu);
        } catch (Exception ex) {
            Logger.getLogger(TestAfipFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        String tipoInscr = categoria;
        if (config != null) {
            if (ca != null) {
                if (tipoInscr.equals("01")) {
                    nFcA_db = config.getNumeroFcA();
                    nNcA_db = config.getNumeroNcA();
                    nFcB_db = config.getNumeroFcB();
                    nNcB_db = config.getNumeroNcB();
                    fcAenDbTxt.setText(df.format(nFcA_db));
                    ncAenDbTxt.setText(df.format(nNcA_db));
                    fcBenDbTxt.setText(df.format(nFcB_db));
                    ncBenDbTxt.setText(df.format(nNcB_db));
                    
                } else {
                    nFcC_db = config.getNumeroFc();
                    nNcC_db = config.getNumeroNc();
                    fcCenDbTxt.setText(df.format(nFcC_db));
                    ncCenDbTxt.setText(df.format(nNcC_db));
                    String certif = ca.getCertificado();
                    String llave = ca.getLlave();
                    String cui1 = cuitTxt.getText();
                    TicketTime tt = UtilAfip.solicitarNuevoTicket(titu, certif, llave);
//                    System.out.println(titu);
//                    System.out.println(certif);
//                    System.out.println(llave);
//                    System.out.println(cui1);
//                    System.out.println(tipoInscr);
//                    System.out.println(tt);
                    if (tt != null) {
                        String ptoVta = titu.getSucursal().toString();
                        int ufc = UtilAfip.getUltimaFcC(ptoVta, cui1, tt.getToken(), tt.getSign());
                        int unc = UtilAfip.getUltimaNcC(ptoVta, cui1, tt.getToken(), tt.getSign());
                        fcCenAfipTxt.setText(df.format(ufc));
                        ncCenAfipTxt.setText(df.format(unc));
//                        System.out.println(tt.getSign());
//                        System.out.println(tt.getToken());
                    }
                    System.out.println("DATOS PROCESADOS");
//                    System.exit(0);
                }
            } else {
                if (ca.getFecha() != null) {
                    Date fe1 = new Date();
                    Date fe2 = ca.getFecha();
                    if (fe1 != fe2) {
                        String certif = ca.getCertificado();
                        String llave = ca.getLlave();
                        String cui1 = cuitTxt.getText();
                        TicketTime tt = UtilAfip.solicitarNuevoTicket(titu, certif, llave);
                        System.out.println(titu);
                        System.out.println(certif);
                        System.out.println(llave);
                        System.out.println(cui1);
                        System.out.println(tipoInscr);
                        System.out.println(tt);
                        if (tt != null) {
                            System.out.println(tt.getSign());
                            System.out.println(tt.getToken());
                        }
                        System.out.println("NUEVO TT CON CA NULL");
                        System.exit(0);
                    }
                }
            }

        } else {
            config = new Configuracion();
            config.setTitular(titu);
            config.setNumeroFc(0);
            config.setNumeroFcA(0);
            config.setNumeroFcB(0);
            config.setNumeroNc(0);
            config.setNumeroNcA(0);
            config.setNumeroNcB(0);
            config.setSucursal(titu.getSucursal());
            try {
                new ConfiguracionService().saveConfiguracion(config);
            } catch (Exception ex) {
                Logger.getLogger(TestAfipFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR GRABANDO CONFIGURACION");
                return;
            }
            

            
        }
    }

//        try {
//            LibraryLoader.loadJacobLibrary();
//            ActiveXComponent wsaa = new ActiveXComponent("WSAA");
//            String wsdl = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
//            String userdir = "c:/certifmario";
//            Dispatch.call(wsaa, "Autenticar",
//                    new Variant("wsfe"),
//                    new Variant(userdir + "/MARIO2020_484132ab2d5e5665.crt"),
//                    new Variant(userdir + "/clave_privada_20142553202_202010295426.key"),
//                    /*
//                    new Variant(userdir + "/nuevo2018_6851c538ff621621.crt"),
//                    new Variant(userdir + "/clave_privada_20142553202_201811010137.key"),
//                     */
//                    new Variant(wsdl));
//            String excepcion = Dispatch.get(wsaa, "Excepcion").toString();
//            System.out.println(excepcion);
//            String token = Dispatch.get(wsaa, "Token").toString();
//            String sign = Dispatch.get(wsaa, "Sign").toString();
////            System.out.println(token);
////            System.out.println(sign);
////            JOptionPane.showMessageDialog(this, "Ver");
//            ActiveXComponent wsfev1 = new ActiveXComponent("WSFEv1");
//            Dispatch.put(wsfev1, "Cuit", new Variant("20142553202"));
//            Dispatch.put(wsfev1, "Token", new Variant(token));
//            Dispatch.put(wsfev1, "Sign", new Variant(sign));
//            String cache = "";
//            wsdl = "https://servicios1.afip.gov.ar/wsfev1/service.asmx?WSDL"; // produccion
//            Dispatch.call(wsfev1, "Conectar",
//                    new Variant(cache),
//                    new Variant(wsdl)
//            );
//            String tipo_cbte = "1";
//            tipo_cbte = "11"; //Factura C
//            String pto_vta = "6"; // Sucursal declarada WS
//            Variant ult = Dispatch.call(wsfev1, "CompUltimoAutorizado",
//                    new Variant(tipo_cbte),
//                    new Variant(pto_vta));
//            excepcion = Dispatch.get(wsfev1, "Excepcion").toString();
////            fcAfipTxt.setText(ult.toString());
//            tipo_cbte = "13"; //Nota Credito C
//            pto_vta = "6"; // Sucursal declarada WS
//            ult = Dispatch.call(wsfev1, "CompUltimoAutorizado",
//                    new Variant(tipo_cbte),
//                    new Variant(pto_vta));
//            excepcion = Dispatch.get(wsfev1, "Excepcion").toString();
////            ncAfipTxt.setText(ult.toString());
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e);
//            e.printStackTrace();
//            return;
//        }
//        Configuracion co = null;
//
//        try {
//            co = new ConfiguracionService().getConfiguracionById(1L);
//        } catch (Exception ex) {
//            Logger.getLogger(TestAfipFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (co
//                != null) {
//            fcAenDbTxt.setText(df.format(co.getNumeroFc()));
//        }
//    }
    private void llenarCombo() {
        titulares = null;
        combo.removeAllItems();
        combo.addItem("");
        try {
            titulares = new TitularCuitService().getAllTitularDeCuitActivos();

        } catch (Exception ex) {
            Logger.getLogger(TestAfipFrame.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        if (titulares != null && !titulares.isEmpty()) {
            for (TitularCuit tc : titulares) {
                combo.addItem(tc.getRazonSocial());
            }
        }
    }

    private void mostrar(int row) {
        titu = titulares.get(row);
        titularTxt.setText(titu.getRazonSocial());
        categoriaTxt.setText(titu.getCategoria());
        String cui1 = titu.getCuit();
        String pri = cui1.substring(0, 2);
        String med = cui1.substring(3, 11);
        String fin = cui1.substring(12, 13);
        String cuit = pri + med + fin;
        cuitTxt.setText(cuit);
        if (titu.getCategoria().equals("01")) {
            categoria = "01";
            mostrar1();
        } else {
            categoria = "04";
            mostrar2();
        }
    }

    private void ocultar1() {
        fcAenDbTxt.setVisible(false);
        ncAenDbTxt.setVisible(false);
        fcBenDbTxt.setVisible(false);
        ncBenDbTxt.setVisible(false);
        fcAenDbLbl.setVisible(false);
        ncAenDbLbl.setVisible(false);
        fcBenDbLbl.setVisible(false);
        ncBenDbLbl.setVisible(false);

        fcAenAfipTxt.setVisible(false);
        ncAenAfipTxt.setVisible(false);
        fcBenAfipTxt.setVisible(false);
        ncBenAfipTxt.setVisible(false);
        fcAenAfipLbl.setVisible(false);
        ncAenAfipLbl.setVisible(false);
        fcBenAfipLbl.setVisible(false);
        ncBenAfipLbl.setVisible(false);
    }

    private void ocultar2() {
        fcCenDbTxt.setVisible(false);
        ncCenDbTxt.setVisible(false);
        fcCenDbLbl.setVisible(false);
        ncCenDbLbl.setVisible(false);

        fcCenAfipTxt.setVisible(false);
        ncCenAfipTxt.setVisible(false);
        fcCenAfipLbl.setVisible(false);
        ncCenAfipLbl.setVisible(false);
    }

    private void mostrar1() {
        fcAenDbTxt.setVisible(true);
        ncAenDbTxt.setVisible(true);
        fcBenDbTxt.setVisible(true);
        ncBenDbTxt.setVisible(true);
        fcAenDbLbl.setVisible(true);
        ncAenDbLbl.setVisible(true);
        fcBenDbLbl.setVisible(true);
        ncBenDbLbl.setVisible(true);

        fcAenAfipTxt.setVisible(true);
        ncAenAfipTxt.setVisible(true);
        fcBenAfipTxt.setVisible(true);
        ncBenAfipTxt.setVisible(true);
        fcAenAfipLbl.setVisible(true);
        ncAenAfipLbl.setVisible(true);
        fcBenAfipLbl.setVisible(true);
        ncBenAfipLbl.setVisible(true);
    }

    private void mostrar2() {
        fcCenDbTxt.setVisible(true);
        ncCenDbTxt.setVisible(true);
        fcCenDbLbl.setVisible(true);
        ncCenDbLbl.setVisible(true);

        fcCenAfipTxt.setVisible(true);
        ncCenAfipTxt.setVisible(true);
        fcCenAfipLbl.setVisible(true);
        ncCenAfipLbl.setVisible(true);
    }
}
